from tkinter import *
from tkinter import ttk
from time import *

root = Tk()
root.title("アプリ")
root.state("zoomed")
root.grid_columnconfigure(0, weight=1)
root.grid_rowconfigure(0, weight=1)

page0 = Frame(root, width=10000, height=5000)
frame0 = Frame(page0, width=10000, height=5000)
class_label = Label(frame0, text="クラス", font=("Arial", 20, "bold"))
class_entry = Entry(frame0, font=("Arial", 20, "bold"))
level_label = Label(frame0, text="レベル", font=("Arial", 20, "bold"))
level_entry = Entry(frame0, font=("Arial", 20, "bold"))
no_label = Label(frame0, text="レッスンNo.", font=("Arial", 20, "bold"))
no_entry = Entry(frame0, font=("Arial", 20, "bold"))
interest_var = BooleanVar()
interest_check = Checkbutton(frame0, text="利子", variable=interest_var, font=("Arial", 20, "bold"))
monthly_var = BooleanVar()
monthly_check = Checkbutton(frame0, text="マンスリーミッション", variable=monthly_var, font=("Arial", 20, "bold"))
pair1_label = Label(frame0, text="ペア1", font=("Arial", 20, "bold"))
pair1_1_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair1_2_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair2_label = Label(frame0, text="ペア2", font=("Arial", 20, "bold"))
pair2_1_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair2_2_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair3_label = Label(frame0, text="ペア3", font=("Arial", 20, "bold"))
pair3_1_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair3_2_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair4_label = Label(frame0, text="ペア4", font=("Arial", 20, "bold"))
pair4_1_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair4_2_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair5_label = Label(frame0, text="ペア5", font=("Arial", 20, "bold"))
pair5_1_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair5_2_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair6_label = Label(frame0, text="ペア6", font=("Arial", 20, "bold"))
pair6_1_entry = Entry(frame0, font=("Arial", 20, "bold"))
pair6_2_entry = Entry(frame0, font=("Arial", 20, "bold"))
page1 = Frame(root, width=10000, height=5000)
frame1 = Frame(page1, width=10000, height=5000)
start_button = Button(frame0, text="開始", command=lambda:page1.tkraise(), font=("Arial", 20, "bold"))
title_label = Label(frame1, text=f"{class_entry}\n({level_entry}:{no_entry})", font=("Arial", 50, "bold"))

page0.grid(column=0, row=0, sticky=NSEW)
frame0.pack()
class_label.grid(column=0, row=0, sticky=W)
class_entry.grid(column=1, row=0, sticky=W)
level_label.grid(column=0, row=1, sticky=W)
level_entry.grid(column=1, row=1, sticky=W)
no_label.grid(column=0, row=2, sticky=W)
no_entry.grid(column=1, row=2, sticky=W)
pair1_label.grid(column=0, row=3, sticky=W)
pair1_1_entry.grid(column=1, row=3, sticky=W)
pair1_2_entry.grid(column=2, row=3, sticky=W)
pair2_label.grid(column=0, row=4, sticky=W)
pair2_1_entry.grid(column=1, row=4, sticky=W)
pair2_2_entry.grid(column=2, row=4, sticky=W)
pair3_label.grid(column=0, row=5, sticky=W)
pair3_1_entry.grid(column=1, row=5, sticky=W)
pair3_2_entry.grid(column=2, row=5, sticky=W)
pair4_label.grid(column=0, row=6, sticky=W)
pair4_1_entry.grid(column=1, row=6, sticky=W)
pair4_2_entry.grid(column=2, row=6, sticky=W)
pair5_label.grid(column=0, row=7, sticky=W)
pair5_1_entry.grid(column=1, row=7, sticky=W)
pair5_2_entry.grid(column=2, row=7, sticky=W)
pair6_label.grid(column=0, row=8, sticky=W)
pair6_1_entry.grid(column=1, row=8, sticky=W)
pair6_2_entry.grid(column=2, row=8, sticky=W)
interest_check.grid(column=0, row=9, sticky=W)
monthly_check.grid(column=0, row=10, sticky=W)
start_button.grid(column=1, row=11)
page1.grid(column=0, row=0, sticky=NSEW)
frame1.pack()
title_label.grid(column=0, row=0)

page0.tkraise()

root.mainloop()